### ISSUE TITLE
continuous integration is not configured

### ISSUE THREAD

**Issue by yegor256** [egis/parent#13]
There has to be some continuous integration service configured. To my knowledge, there is nothing right now. Here is a list of possible options: http://www.yegor256.com/2014/10/05/ten-hosted-continuous-integration-services.html

**Comment by yegor256** [comment]
@Egis-Moshe I think this task is for you now. I would recommend to chose Travis. If you already have something configured, please let me know.

**Comment by Egis-Moshe** [comment]
@yegor256 we use CircleCI you should have access already

**Comment by yegor256** [comment]
@Egis-Moshe I'm getting this page:

<img width="1427" alt="screen shot 2016-07-21 at 7 13 42 pm" src="https://cloud.githubusercontent.com/assets/526301/17044716/75f1c290-4f77-11e6-8e7e-2bafcc4d4e00.png">


I think you should take a look at the account configuration. Also, if it's still an option to select another CI provider, please consider this comparison: http://www.yegor256.com/2014/10/05/ten-hosted-continuous-integration-services.html If not, we can live with CircleCI, it's not critical.

**Comment by Egis-Moshe** [comment]
@yegor256 I think your review is a bit out of date - circleci supports both PR's and iOS builds.  It is also much cheaper the travis.

Check under the Builds -> egis tab a circleci.yml would need to be added to egis/parent for it to build

**Comment by yegor256** [comment]
@Egis-Moshe I added `circle.yml`, but I think you have to activate the project, see:

<img width="1433" alt="screen shot 2016-07-22 at 12 42 05 pm" src="https://cloud.githubusercontent.com/assets/526301/17069129/c7df071a-5009-11e6-92ee-8ddcec758d65.png">

**Comment by Egis-Moshe** [comment]
@yegor256 done

**Comment by yegor256** [comment]
@Egis-Moshe good thanks
